<?xml version="1.0" encoding="UTF-8"?>
<!--

    SPDX-FileCopyrightText: Copyright © 2021 Red Hat, Inc., and individual contributors as indicated by the @author tags.
    SPDX-License-Identifier: Apache-2.0

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.jboss.pnc.rex</groupId>
    <artifactId>parent</artifactId>
    <version>1.2.4-SNAPSHOT</version>
  </parent>

  <artifactId>rex-common</artifactId>
  <name>rex-common</name>

  <properties>
    <maven.compiler.release>11</maven.compiler.release>
  </properties>
  <dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-infinispan-client</artifactId>
      <optional>true</optional>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>io.github.git-commit-id</groupId>
        <artifactId>git-commit-id-maven-plugin</artifactId>
        <version>10.0.1</version>

        <configuration>
          <!--
                      If you'd like to tell the plugin where your .git directory is,
                      use this setting, otherwise we'll perform a search trying to
                      figure out the right directory. It's better to add it explicite IMHO.
                    -->
          <dotGitDirectory>${project.basedir}/.git</dotGitDirectory>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>revision</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>com.google.code.maven-replacer-plugin</groupId>
        <artifactId>maven-replacer-plugin</artifactId>
        <version>1.4.1</version>
        <configuration>
          <file>src/main/templates/org/jboss/pnc/rex/common/Constants.java</file>
          <outputFile>src/main/java/org/jboss/pnc/rex/common/Constants.java</outputFile>
          <replacements>
            <replacement>
              <token>@version-rex@</token>
              <value>${project.version}</value>
            </replacement>
            <replacement>
              <token>@commit-id@</token>
              <value>${git.commit.id.abbrev}</value>
            </replacement>
            <replacement>
              <token>@build-time@</token>
              <value>${maven.build.timestamp}</value>
            </replacement>
          </replacements>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>replace</goal>
            </goals>
            <phase>process-sources</phase>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
