scheduler:
  baseUrl: http://localhost:8082
  options:
    task-configuration:
      clean: false

disable:
  authorization: true
quarkus:
  oidc:
    enabled: false
    auth-server-url: ""
  oidc-client:
    enabled: false
  transaction-manager:
    default-transaction-timeout: 10m
  otel:
    enabled: true
    resource:
      attributes: deployment.environment=dev,service.name=REX
  http:
    port: 8082
  smallrye-openapi:
    store-schema-directory: ""
  infinispan-client:
    use-schema-registration: true
    use-auth: true
    username: admin
    password: password
    cache:
      "rex-counter":
        configuration-resource: "counter-configuration.xml"
        near-cache-mode: disabled
      "rex-tasks":
        configuration-resource: "task-configuration.xml"
        near-cache-mode: invalidated
      "rex-constraints":
        configuration-resource: "constraints-configuration.xml"
        near-cache-mode: invalidated
      "rex-signals":
        configuration-resource: "signals-configuration.xml"
        near-cache-mode: disabled
      "rex-cluster-jobs":
        configuration-resource: "cluster-jobs-configuration.xml"
        near-cache-mode: disabled
    devservices:
      image-name: "quay.io/infinispan/server:15.0.15.Final"
      config-files: infinispan-devservice-config.xml
    tracing:
      propagation:
        enabled: true
  devservices:
    launch-on-shared-network: true
  log:
    category:
      "org.jboss.pnc":
        level: TRACE
      "io.quarkus.infinispan":
        level: TRACE
      "io.opentelemetry":
        level: INFO
    min-level: FINEST
