scheduler:
  baseUrl: http://localhost:8081
  options:
    task-configuration:
      heartbeat:
        processing-tolerance: 50ms
    http-configuration:
      request-retry-policy:
        backoff:
          min-delay: 10ms
          max-delay: 10ms
        max-retries: 5
      status-code-retry-policy:
        4xx:
          backoff:
            min-delay: 10ms
            max-delay: 10ms
          max-retries: 5
        404:
          max-retries: 0
        403:
          max-retries: 0
        425:
          backoff:
            min-delay: 10ms
            max-delay: 10ms
          expire-in: 4900ms
        429:
          backoff:
            min-delay: 10ms
            max-delay: 10ms
          max-retries: 5
        5xx:
          backoff:
            min-delay: 10ms
            max-delay: 10ms
          max-retries: 5
        599:
          backoff:
            min-delay: 10ms
            max-delay: 10ms
          max-retries: 5

quarkus:
  keycloak:
    devservices:
      enabled: false
  log:
    category:
      "org.testcontainers":
        level: INFO
      "io.quarkus.infinispan.client":
        level: INFO
  smallrye-openapi:
    store-schema-directory: ""
  oidc:
    enabled: false
    auth-server-url: ""
  oidc-client:
    enabled: false
  transaction-manager:
    default-transaction-timeout: 10m
  http:
    port: 8081
  otel:
    enabled: true
    exporter:
      otlp:
        traces:
          endpoint: http://localhost:4317
    traces:
      exporter: cdi
      enabled: true
  observability:
    enabled: false
  infinispan-client:
    use-schema-registration: true
    use-auth: true
    username: admin
    password: password
    tracing:
      propagation:
        enabled: true
    devservices:
      config-files: infinispan-devservice-config.xml
      image-name: "quay.io/infinispan/server:15.0.15.Final"
      tracing:
        enabled: false